TEST_DATABASE = [
    #MPB e Bossa
    ("https://www.cifraclub.com.br/djavan/oceano/", 'D'),
    ("https://www.cifraclub.com.br/djavan/sina/", 'A'),
    ("https://www.cifraclub.com.br/djavan/eu-te-devoro/", 'D'),
    ("https://www.cifraclub.com.br/djavan/se/", 'A'),
    ("https://www.cifraclub.com.br/djavan/flor-de-lis/", 'C'),

    ("https://www.cifraclub.com/rodrigo-amarante/tuyo/", 'Am'),
    ("https://www.cifraclub.com/ze-ramalho/chao-de-giz/", 'G'),
    ("https://www.cifraclub.com/adriana-calcanhotto/fico-assim-sem-voce/", 'A'),
    ("https://www.cifraclub.com/alceu-valenca/anunciacao/", 'G'),
    ("https://www.cifraclub.com/alceu-valenca/la-belle-du-jour/", 'C'),

    ("https://www.cifraclub.com.br/baden-powell/canto-de-ossanha/", 'Dm'),
    ("https://www.cifraclub.com.br/baden-powell/samba-em-preludio/", 'Bm'),
    ("https://www.cifraclub.com.br/baden-powell/berimbau/", 'Dm'),
    ("https://www.cifraclub.com.br/baden-powell/tristeza-solidao/", 'Dm'),
    ("https://www.cifraclub.com.br/baden-powell/samba-triste/", 'Am'),

    ("https://www.cifraclub.com.br/vinicius-de-moraes/onde-anda-voce/", 'C'),
    ("https://www.cifraclub.com.br/vinicius-de-moraes/garota-de-ipanema/", 'F'),
    ("https://www.cifraclub.com.br/vinicius-de-moraes/chega-de-saudade/", 'D'),
    ("https://www.cifraclub.com.br/vinicius-de-moraes/pela-luz-dos-olhos-teus/", 'F'),
    ("https://www.cifraclub.com.br/vinicius-de-moraes/eu-sei-que-vou-te-amar/", 'F'),

    ("https://www.cifraclub.com.br/toquinho/aquarela/", 'G'),
    ("https://www.cifraclub.com.br/toquinho/caderno/", 'Gm'),
    ("https://www.cifraclub.com.br/toquinho/era-uma-casa/", 'A'),
    ("https://www.cifraclub.com.br/tom-jobim/aguas-de-marco/", 'B'),
    ("https://www.cifraclub.com.br/caetano-veloso/sozinho/", 'D'),

    ("https://www.cifraclub.com.br/caetano-veloso/voce-linda/", 'A'),
    ("https://www.cifraclub.com.br/caetano-veloso/voce-nao-me-ensinou-te-esquecer/", 'Cm'),
    ("https://www.cifraclub.com.br/5-seco/pra-voce-dar-o-nome/", 'E'),
    ("https://www.cifraclub.com.br/5-seco/feliz-pra-cachorro/", 'Em'),
    ("https://www.cifraclub.com/marcelo-camelo/janta/", 'C'),

    ("https://www.cifraclub.com/marcelo-camelo/luzes-da-cidade/", 'C'),
    ("https://www.cifraclub.com/marcelo-camelo/doce-solidao/", 'A'),
    ("https://www.cifraclub.com/marcelo-camelo/cade-teu-suin/", 'Am'),
    ("https://www.cifraclub.com/marcelo-camelo/cara-valente/", 'F#'),
    ("https://www.cifraclub.com/marcelo-camelo/pois-e/", 'Em'),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    #Velha Guarda
    ("https://www.cifraclub.com.br/roberto-carlos/como-grande-meu-amor-por-voce/", 'F'),

    ("https://www.cifraclub.com.br/roberto-carlos/detalhes/", 'A'),
    ("https://www.cifraclub.com.br/roberto-carlos/como-vai-voce/", 'A'),
    ("https://www.cifraclub.com.br/roberto-carlos/debaixo-dos-caracois-dos-seus-cabelos/", 'A'),
    ("https://www.cifraclub.com.br/roberto-carlos/jesus-cristo/", 'Em'),
    ("https://www.cifraclub.com.br/erasmo-carlos/sentado-a-beira-do-caminho/", 'C'),

    ("https://www.cifraclub.com.br/erasmo-carlos/pode-vir-quente-que-eu-estou-fervendo/", 'Am'),
    ("https://www.cifraclub.com.br/erasmo-carlos/a-carta/", 'F'),
    ("https://www.cifraclub.com.br/roberto-carlos/o-calhambeque-road-hog/", 'F#'),
    ("https://www.cifraclub.com.br/roberto-carlos/parei-na-contramao/", 'B'),
    ("https://www.cifraclub.com.br/roberto-carlos/e-preciso-saber-viver/", 'E'),
    #Jazz
    ("https://www.cifraclub.com.br/chet-baker/i-fall-in-love-too-easily/", 'D#'),
    ("https://www.cifraclub.com/frank-sinatra/fly-me-to-the-moon/", 'C'),
    ("https://www.cifraclub.com/frank-sinatra/my-way/", 'C'),
    ("https://www.cifraclub.com/frank-sinatra/killing-me-softly/", 'G#m'),
    ("https://www.cifraclub.com/louis-armstrong/what-wonderful-world/", 'F'),

    ("https://www.cifraclub.com/eric-clapton/autumn-leaves/", 'Bm'),
    #R&B, Funk e Soul
    ("https://www.cifraclub.com/bill-withers/aint-no-sunshine/", 'Am'),
    ("https://www.cifraclub.com/bill-withers/lovely-day/", 'E'),
    ("https://www.cifraclub.com/james-brown/i-got-you-i-feel-good/", 'D'),
    ("https://www.cifraclub.com/marvin-gaye/aint-no-mountain-high-enough/", 'Cm'),

    ("https://www.cifraclub.com/marvin-gaye/lets-get-it-on/", 'D'),
    ("https://www.cifraclub.com/marvin-gaye/sexual-healing/", 'A'),
    ("https://www.cifraclub.com/rick-james/ebony-eyes/", 'D'),
    ("https://www.cifraclub.com/temptations/my-girl/", 'C'),
    ("https://www.cifraclub.com/kool-and-the-gang/celebration/", 'G#'),

    ("https://www.cifraclub.com/ben-e-king/stand-by-me/", 'A'),
    ("https://www.cifraclub.com/earth-wind-and-fire/september/", 'A'),
    ("https://www.cifraclub.com/earth-wind-and-fire/lets-groove/", 'Bm'),
    #Rock em geral
    ("https://www.cifraclub.com/queen/bohemian-rhapsody/", 'G'),
    ("https://www.cifraclub.com/queen/love-of-my-life/", 'D'),

    ("https://www.cifraclub.com/pink-floyd/wish-you-were-here/", 'G'),
    ("https://www.cifraclub.com/the-eagles/hotel-california/", 'Bm'),
    ("https://www.cifraclub.com/elvis-presley/cant-help-falling-in-love/", 'C'),
    ("https://www.cifraclub.com/oasis/wonderwall/", 'Em'),
    ("https://www.cifraclub.com/the-beatles/hey-jude/", 'F'),

    ("https://www.cifraclub.com/the-beatles/let-it-be/", 'C'),
    ("https://www.cifraclub.com/creedence-clearwater-revival/have-you-ever-seen-the-rain/", 'C'),
    ("https://www.cifraclub.com/the-beatles/yesterday/", 'G'),
    ("https://www.cifraclub.com/john-lennon/imagine/", 'C'),
    ("https://www.cifraclub.com/the-cranberries/zombie/", 'Em'),

    ("https://www.cifraclub.com/extreme/more-than-words/", 'G'),
    ("https://www.cifraclub.com/radiohead/creep/", 'G'),
    ("https://www.cifraclub.com/audioslave/like-stone/", 'Em'),
    ("https://www.cifraclub.com/rem/losing-my-religion/", 'Em'),
    ("https://www.cifraclub.com/passenger/let-her-go/", 'Am'),

    ("https://www.cifraclub.com/4-non-blondes/whats-up/", 'A'),
    ("https://www.cifraclub.com/hozier/take-me-to-church/", 'Em'),
    ("https://www.cifraclub.com/kings-of-leon/use-somebody/", 'C'),
    ("https://www.cifraclub.com/radiohead/high-and-dry/", 'E'),
    ("https://www.cifraclub.com/radiohead/no-surprises/", 'F'),

    ("https://www.cifraclub.com/radiohead/fake-plastic-trees/", 'A'),
    ("https://www.cifraclub.com/los-hermanos/sentimental/", 'F'),
    ("https://www.cifraclub.com/los-hermanos/a-flor/", 'G#m'),
    ("https://www.cifraclub.com/los-hermanos/alem-do-que-se-ve/", 'A'),
    ("https://www.cifraclub.com/los-hermanos/veja-bem-meu-bem/", 'Am'),

    ("https://www.cifraclub.com/los-hermanos/retrato-pra-iaia/", 'E'),
    ("https://www.cifraclub.com/los-hermanos/casa-pre-fabricada/", 'A'),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

]