TEST_DATABASE = [
    #MPB e Bossa
    ("https://www.cifraclub.com.br/djavan/oceano/", 'D'),
    ("https://www.cifraclub.com.br/djavan/sina/", 'A'),
    ("https://www.cifraclub.com.br/djavan/eu-te-devoro/", 'D'),
    ("https://www.cifraclub.com.br/djavan/se/", 'A'),
    ("https://www.cifraclub.com.br/djavan/flor-de-lis/", 'C'),

    ("https://www.cifraclub.com.br/baden-powell/canto-de-ossanha/", 'Dm'),
    ("https://www.cifraclub.com.br/baden-powell/samba-em-preludio/", 'Bm'),
    ("https://www.cifraclub.com.br/baden-powell/berimbau/", 'Dm'),
    ("https://www.cifraclub.com.br/baden-powell/tristeza-solidao/", 'Dm'),
    ("https://www.cifraclub.com.br/baden-powell/samba-triste/", 'Am'),

    ("https://www.cifraclub.com.br/vinicius-de-moraes/onde-anda-voce/", 'C'),
    ("https://www.cifraclub.com.br/vinicius-de-moraes/garota-de-ipanema/", 'F'),
    ("https://www.cifraclub.com.br/vinicius-de-moraes/chega-de-saudade/", 'D'),
    ("https://www.cifraclub.com.br/vinicius-de-moraes/pela-luz-dos-olhos-teus/", 'F'),
    ("https://www.cifraclub.com.br/vinicius-de-moraes/eu-sei-que-vou-te-amar/", 'F'),

    ("https://www.cifraclub.com.br/toquinho/aquarela/", 'G'),
    ("https://www.cifraclub.com.br/toquinho/caderno/", 'Gm'),
    ("https://www.cifraclub.com.br/toquinho/era-uma-casa/", 'A'),
    ("https://www.cifraclub.com.br/tom-jobim/aguas-de-marco/", 'B'),
    ("https://www.cifraclub.com.br/caetano-veloso/sozinho/", 'D'),

    ("https://www.cifraclub.com.br/caetano-veloso/voce-linda/", 'A'),
    ("https://www.cifraclub.com.br/caetano-veloso/voce-nao-me-ensinou-te-esquecer/", 'Cm'),
    ("https://www.cifraclub.com.br/5-seco/pra-voce-dar-o-nome/", 'E'),
    ("https://www.cifraclub.com.br/5-seco/feliz-pra-cachorro/", 'Em'),
    #Velha Guarda
    ("https://www.cifraclub.com.br/roberto-carlos/como-grande-meu-amor-por-voce/", 'F'),

    ("https://www.cifraclub.com.br/roberto-carlos/detalhes/", 'A'),
    ("https://www.cifraclub.com.br/roberto-carlos/como-vai-voce/", 'A'),
    ("https://www.cifraclub.com.br/roberto-carlos/debaixo-dos-caracois-dos-seus-cabelos/", 'A'),
    ("https://www.cifraclub.com.br/roberto-carlos/jesus-cristo/", 'Em'),
    ("https://www.cifraclub.com.br/erasmo-carlos/sentado-a-beira-do-caminho/", 'C'),

    ("https://www.cifraclub.com.br/erasmo-carlos/pode-vir-quente-que-eu-estou-fervendo/", 'Am'),
    ("https://www.cifraclub.com.br/erasmo-carlos/a-carta/", 'F'),
    ("https://www.cifraclub.com.br/roberto-carlos/o-calhambeque-road-hog/", 'F#'),
    ("https://www.cifraclub.com.br/roberto-carlos/parei-na-contramao/", 'B'),
    ("https://www.cifraclub.com.br/roberto-carlos/e-preciso-saber-viver/", 'E'),
    #Jazz
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),
    ("", ''),

]